#!/bin/bash

usage() {
    echo "[USAGE]: $0 -n name -t -b/-a -l"
}

[[ "$#" -eq 0 ]] && echo "No args specified, using base mode" && usage && BASE_MODE="true"

if [ ! -d ".git" ]; then
    echo "Info: Not a git repo"
fi

# default values
SRC="src"
INCLUDE="include"
DIR="project"
TEMPLATES="$HOME/cloned/new_workspace_creator/templates"
BINARY_MAKEFILE="false"
ARCHIVE_MAKEFILE="false" 
UNIT_TESTS=false

# argparser
while getopts "n:bat" opt; do
  case $opt in
    n) DIR="$OPTARG" ;;
    b) BINARY_MAKEFILE="true" ;;
    a) ARCHIVE_MAKEFILE="true" ;;
    t) UNIT_TESTS=true ;;
    *) usage; exit 1 ;;
  esac
done

# incompatible flags check
if [[ "$BINARY_MAKEFILE" == "true" && "$ARCHIVE_MAKEFILE" == "true" ]]; then
    echo "Cannot use both -b and -a"
    usage
    exit 2
fi

[[ "$BINARY_MAKEFILE" == "true" ]] || [[ "$BASE_MODE" == "true" ]] && cp "$TEMPLATES/Binary_Makefile" "Makefile" 2>/dev/null && mkdir -p lib
[[ "$ARCHIVE_MAKEFILE" == "true" ]] && cp "$TEMPLATES/Archive_Makefile" "Makefile" 2>/dev/null

mkdir -p "$SRC" "$INCLUDE"

[[ "$UNIT_TESTS" == "true" ]] && mkdir -p unit_tests

genheader "$DIR" >> "$SRC/main.c"
genmain >> "$SRC/main.c"
geninclude "$DIR" >> "$INCLUDE/$DIR.h"
